#+TITLE: Netorare
(visual-line-mode)
- tag search in anime-hentai: https://theindex.moe/library/hentai
- imgur grid layout https://imgur.com/a/NUMBER/layout/grid

* NTR LITERATURE
https://chyoa.com/story/Being-an-adventurer-is-not-always-the-best.29686
[IsekaiNTR] When I was summoned to another world with RPG style, [Likes NTR] skill appeared.
https://isekaintr.wordpress.com/when-i-was-summoned-to-another-world-likes-ntr-skill-appeared/
[IcedKafuuChino] My Childhood Friend is the Hero's Bride
https://childhoodfriendpublications.wordpress.com/
RPG goddess of darkness summon, but cursed with NTR fetish
https://isekaintr.wordpress.com/when-i-was-summoned-to-another-world-likes-ntr-skill-appeared/
* NTR ANIMES | HENTAI
** Kaifuku Jutsushi no Yarinaoshi
   raped hero returns in time to get revenge on the people that took advantage of him by raping them
** Ishuzoku Reviewers
   actual heroes earl money by making reviews of the burdels of other species
** Ajisai no Chiru Koro ni
based on hentai same name
https://hentaihaven.xxx/watch/ajisai-no-chiru-koro-ni/episode-1/
** Queen's Blade s1 s2
** Uchi no Otouto Maji de Dekain dakedo Mi ni Konai?
https://hentaiworld.tv/hentai-videos/uchi-no-otouto-maji-de-dekain-dakedo-mi-ni-konai-episode-1/
** Hitou Meguri Kakure Yu Mao Hen
cucked while on dates and later even on vacation; at the end discoverered
https://hentaila.com/ver/hitou-meguri-kakure-yu-mao-hen-1
** OtomeDori
pink haired mom is secretly a slut for gangbangs of old men, pregnant because of that (later daughter too ); maybe, just maybe, hubby is imagining all
** Tsuma ga Kirei ni Natta Wake 2
netori
https://hanime.tv/videos/hentai/tsuma-ga-kirei-ni-natta-wake-2
** Toshoshitsu no Kanojo Seiso na Kimi ga Ochiru made
[[id:b7fba639-55ba-4db0-a264-d7b8e7fd0a4a][NTR FAV/[AMAM (Ame Arare)] Toshoshitsu No Kanojo ~Seiso Na Kimi Ga Ochiru Made~]]
https://hentaiworld.tv/hentai-videos/toshoshitsu-no-kanojo-seiso-na-kimi-ga-ochiru-made-episode-3/
** Tsuma ga Kirei ni Natta Wake
opens eyes facing hubby instead of alfa, truth unraveled
https://hanime.tv/videos/hentai/tsuma-ga-kirei-ni-natta-wake-1
https://hanime.tv/videos/hentai/tsuma-ga-kirei-ni-natta-wake-2

* LITEROTICA
- https://darkwanderer.net/ams/the-wedding-conception.7835/
  - accientest 1999, He encourages her to go with the former rival, held at a hotel, She ends up getting pregnant
** FEMINIST
https://www.literotica.com/s/bully-claimed-my-wife-at-reunion
https://www.asstr.org/files/Authors/Stormbringer/The%20Unwanted%20Houseguest.txt
https://www.literotica.com/s/hipster-chicks-love-big-dicks
https://www.literotica.com/s/a-wife-turned :sluttified:
https://www.literotica.com/s/she-opened-my-mind
- russian convinces bf to let her breed better
- has sex at bf family meeting, bf guards others away
** WEDDING  / HONEYMOON
https://www.literotica.com/s/we-are-waiting-until-marriage :virgin:
https://www.literotica.com/s/he-fucked-my-girl :jenny:scott:alice:
https://www.obliviouscuckold.com/cuckolded-at-my-own-bachelor-party-wedding-and-honeymoon/
https://www.literotica.com/s/hired-by-my-fiances-ex-ch-01 :gym:denied:
https://www.literotica.com/s/the-nerd-pt-01 :honeymoonwithelse:
https://www.literotica.com/s/the-honeymoon-11
- (cuck)beta wedding, gf and alfa make out to all-surprise
- leave beta to explain the situation, openly leaving to enjoy the honeymoon
https://www.literotica.com/s/cucked-in-the-tropics-ch-01
- at honeymoon she witnesses black casually-fucking petite-cheating-asian
- the asian slowly convinces her to cheat(later cuck) her new hubby
- jackal54641
https://literotica.com/s/selling-our-honeymoon (bending contract limits)
https://www.literotica.com/s/andy-and-stephanie-pt-01
- a small dicked man marries the size queen of his dreams
- accidentally(at first) delays the wedding night, bf outed from the hotel
** TRIP
https://www.literotica.com/s/donna-goes-camping-pt-01
https://www.literotica.com/s/cucking-the-snowbound-couple
- jackal54641
https://ourhotwives.org/forum/viewtopic.php?f=8&t=44432&p=761747#p761747 Faithful Wife's Fall From Grace :chastity:jenny:scott:
https://gustavjorgensonauthor.wordpress.com/2020/04/11/beach-rental/
- alfa gets to sleep in bed with wife, pretend nothing happening (at first)
- what is happening in the bathroom? a secret
** NEIGHBOUR
https://www.literotica.com/s/new-neighbors-12 :fav:
- gf comes to practice with alfa expanding her vagina
- amiga gifts her one of her "please breed me" since she was too
- near-bf release gf decides to breed with alfa instead at public party
https://www.asstr.org/files/Authors/PenPal/Good%20Neighbor%20Sam.txt :alltheneighbourhood:
https://www.obliviouscuckold.com/cuckolded-and-humiliated-by-the-frat-boy-next-door/
https://www.literotica.com/s/irresistible-impulse :ukreseacher:
https://www.literotica.com/s/wife-grudge-fucked-in-courtyard
https://www.literotica.com/s/catching-the-wife-vol-01 :thatsmywife:
https://www.literotica.com/s/my-wifes-big-mouth-1
- chesty barking, fulfills bet, refused to leave while bf had to drop kids
https://www.literotica.com/s/roys-conquests-hot-for-teacher
- alfa uses beta as pretext to get beta-crush to cheat, but then claims her all for himself, beta was merely a tool
NEIGHBOUR CHRONICLES
https://www.literotica.com/s/neighbor-chronicles-pt-01
- ugly bastard with big cock as neighbour, fat and older
- hubby with cuck fantasies, bastard tought at first she was cheating
- only bastard has ever got a blowjob from wife, and will get her ass first
https://www.literotica.com/s/neighbor-chronicles-pt-04
- hubby asked her to be lewd with neighbour, gone wrong
- alfa tought she was cheating, then found out; sex at uber
- alfa drugs beta so he can enjoy wife special lingerine
  - first time, all night, things never done with beta
** FAMILY
https://www.asstr.org/~Kristen/09/brother.txt
- bf infertile, bf-mom arranges (with sister help) for brother to fullfill
https://www.asstr.org/~Kristen/51/partners.txt :getsallthefemales:
https://www.literotica.com/s/an-unwanted-affair
- father impregnated daughter in law of useless son, no sex for one year
https://www.literotica.com/s/home-for-the-holidays-30
- black takes mother, then takes sister
- brother makes mistake of bringing gf and black takes her too
- years later same with fiance
  - who doesnt leave him and instead gets pregnant twice
https://www.literotica.com/s/family-skeleton
- twins pregnant repeatedly, bf hears one thank the other for letting her-bf impregnate her since hers couldnt
  - bf at first thinks that he was the lucky one
  - but years later finds out alfa may had been the one to impregnate gf first (as got inside first)
- https://www.literotica.com/s/accidental-fem-dom-ch-01
  - while gf out on trip and broken-arms, sister-in-law ends up taking care of bf
    - slowly femdoms him, when gf comes back sister arranges for her black bf to cuck
FAMILY TOO
https://www.literotica.com/s/he-let-them-have-me-01
- bf convinces gf into it, later daughters catch on and want to try
https://www.literotica.com/s/the-good-guy-always-loses-ch-01
- bully steal first gf (feels guilty) and then sister too (doesnt)
*OBLIVIOUS DAD CAKE
https://www.literotica.com/s/a-moms-symbol
- two years ago beta stood up to alfa, worst mistake, now mom protects son from alfa who still occasionally beats beta up
  - the sister joins in later, found mom cheating and was going to call someone but alfa dick hypnoptised her
  - beta eventually accepts cuckoldry, arranges for sis to fuck on her birthday
    - sis feeds dad cake with cum
*25 YEARS
https://web.archive.org/web/20131201005841/http://www.literotica.com/s/bully-takes-three
- mom, wife, daughter fall for tattoed alfa
- beta had lied about bully actually being his friend, wife made bf go to school reunion where she got seduced and stayed the night with alfa and slut, daughter refuses to listen dad worries when he found out and ends up getting pregnant
*3 WIFES
https://www.literotica.com/s/reunited-18
https://unrelentingcruelty.wordpress.com/category/series/reunited/reunited-1/
- 3 wifes fall pray for alfa, later also daughter
*LESBIAN: SISTER AND TWO EX-WIFES
- https://www.literotica.com/s/sexy-sadistic-bitches
- first wife is sadistic and takes bf-sister too
- years later bf mans up and divorses her, gets a new cutie as second wife
- first hears and then pushes to become friend and then have sex with her
- divoreses bf, first marries second, and the three girls stick together
UNWANTED HOUSEGUEST
https://www.asstr.org/files/Authors/Stormbringer/The%20Unwanted%20Houseguest.txt
https://www.literotica.com/s/the-unwanted-houseguest
- feminist, her husbands brother completely slutifies her, bf oblivious
CHELSEA
https://candycigars.webflow.io/chelsea
Chelsea/Cameron story from candycigars on Reddit
https://www.reddit.com/r/cuckoldstories/comments/iuttb3/chelsea_cameron_part_4_of_how_i_accidentally_got/
https://candycigars.webflow.io/chelsea
https://www.reddit.com/r/cuckoldstories/comments/i2dqrh/story_of_the_month/g0adwdx/?utm_source=share&utm_medium=ios_app&utm_name=iossmf
*RACHEL
- bf hears them through stream that didnt end
  https://candycigars.webflow.io/rachel
** ALFA WOMAN
https://www.literotica.com/s/donnas-destitute-cuckold :ex:
https://www.literotica.com/s/denial-ch-01 :lesbianfemdom:
https://www.literotica.com/s/replaced-ch-01 :vincetakesfamily:
https://www.literotica.com/s/the-bitch-roomate :herfriendmakeshercheat:
https://www.literotica.com/s/journey-of-our-flm-ch-05 :femaleleadmarriageorbust:
https://www.literotica.com/s/the-young-mans-boat :wifecheatsandhubbygetsrejected:
https://www.literotica.com/s/the-audio-cuckold :herfriendsmakeheraslut:
** BOSS
https://www.literotica.com/s/big-brother-boss-ch-01 :nosexchip:
https://www.literotica.com/s/lapdancing-girlfriend-ch-01 :bullybuysherworkplace:
https://www.literotica.com/s/liberal-leanings :snowbunnygetspregnant:
https://www.literotica.com/s/office-work-ch-01 :officeslut:
https://www.literotica.com/s/a-storm-of-submission :black:nomanup:
https://www.literotica.com/s/you-dont-deserve-my-pussy
https://www.literotica.com/s/the-janitors-wife :privateclub:
https://www.literotica.com/s/hired-by-my-fiances-ex-ch-01 :unfitrealization:
- keeps bf at work while alfa re-engages with bf fiance
https://www.literotica.com/s/seven-days-ch-01-1
- she losses no fuck again bet, fucks alfa at her annibirthery, so to-be-boss wins
** BOSS BLACKMAIL
https://www.literotica.com/s/risking-judy-ch-01 :fav:
https://www.literotica.com/s/robert-and-alexis-pt-01 :fav:virgin:
https://www.asstr.org/~Kristen/55/myrival.txt :colegiala:
** ROOMATE / HOUSEGUEST
https://www.literotica.com/s/cucked-by-our-refugee-pt-01
https://www.literotica.com/s/the-lodger-from-hell
https://www.literotica.com/s/fresh-pt-01 :blackedcollage:
https://www.literotica.com/s/second-place :virgin:
- amiga shaers her bf with gf, virgin bf will go seconds
https://www.literotica.com/s/the-rule-ch-01
- two couples as roomates, one dominates, beta couple starts with rules(deal)
  - gf really gets into it, full blowjobs while beta is allowed to lick like a dog
  - amiga takes beta away for a week leaving alfa-gf alone during it
https://www.literotica.com/s/my-couch
- exchange student, gf wants baby, slowly denies bf who slowly realizes the whole affair but just lets it keep going even when it becomes blatant
https://chyoa.com/story/Can%27t-we-let-him-stay.54001
- former bully of both arrives to their home seeking forgiveness but actually asking them for refugee
- compasionate and drunk gf lets him stay
FIRST STORIES
https://literotica.com/s/my-roommate-wins
- redhead with black, both popular, keep fucking for months beta there
https://www.literotica.com/s/roommate-relations-ch-01
- next door bully seduces gf, convinces her of keep dating beta so she keeps cheating
- a year without fucking, bf kept awake by sounds next door
- breakup while bf chained at chair
GF CRUEL
http://www.obliviouscuckold.com/our-tenant-gave-something-big-to-my-wife-now-lives-rent-free/
- gf lets bully sleep with her because he is injured, for six months
*NATURAL CONSECUENCES
- https://www.literotica.com/s/natural-consequences?page=1
- first gf discovered how sadistic she was, later helps alfa steal second angelic gf
- alfa takes second because bf broke the friendship and gf had tried to humilliate(lecture) him
- https://www.literotica.com/s/natural-consequences-act-03
- third gf too, the day she becomes her gf beta lets her fuck alfa so that gf understands beta-weaknesses
- when beta braves up to stop being a cuck he is gang-cucked back into cuck
** OBLIVIOUS
https://www.literotica.com/s/elise-and-emily-ch-01 :bfmissunderstands:
https://www.literotica.com/s/decorating-the-newlywed
- bf sees it but mistakes semen for paint; alfa was helping painting
https://www.literotica.com/s/firemans-carnival :infrontof:
https://www.literotica.com/s/office-party-and-musical-chairs :shefallsondick:
https://www.literotica.com/s/tainted-conception
- coworker rival dresses like husband and fucks her while oblivious husband is distracted playing with vr at halloween party
NOT RECOGNIZED
https://www.literotica.com/s/house-party-9
- amiga helps her cheat by keeping bf away
- next day bf hears her but fails to recognize her sounds
https://www.literotica.com/s/a-controlling-interest?page=1
- bf cheers on sounds of couple getting fucked at company-party
** SLUTTY GIRL
https://www.literotica.com/s/my-roommate-takes-my-girlfriend :becky:
- several other stories; she cucks him at trip and party too
https://www.literotica.com/s/becky-goes-on-vacation :bfupstairs:
https://www.literotica.com/s/just-one-of-the-guys-ch-06a
- at vacation (with male friends) gf keeps crossing bf redlines
https://www.literotica.com/s/my-girlfriend-joins-the-rugby-team
https://www.literotica.com/s/the-big-bad-rick-wolfe
- all females give in: gf, her amigas(even the shy), and teacher
- gf decides she wants to slut around the world, beta not enough
- alfa tattoes all who sleep with him
https://www.literotica.com/s/my-latin-wife-a-fantasy-born-ch-01-08 :hubbyfetish:
https://www.literotica.com/s/michelles-river-exploration :riverparty:
** OUT OF CONTROL
https://www.literotica.com/s/patriotic-duty :fbi:
https://www.literotica.com/s/julia-the-patriot :soldier:
https://www.literotica.com/s/you-should-leave :threesomeattemptseveraltimes:
https://www.literotica.com/s/interception-1 :footballstarstealswife:
https://www.literotica.com/s/valentines-interrupted :bfbirthday:sisterinlawbf:
https://www.literotica.com/s/camping-curiosity
- squeezed in tent with friend(alfa), whose dick pops out of pants and inside gf
PRETEND NOT TO BE COUPLE
https://www.literotica.com/s/the-part-time-assistant
- she pretended to be lesbian to get job
https://www.literotica.com/s/my-wife-honey
- pretended to be sister-brother, trying to close a deal
- alfa wants to impregnate her, gf doesnt believe bf tho thinks its jealous
https://www.literotica.com/s/laceys-date-night
- lended, pretends to be friend-gf; ends up going for real
** BACHELORETE
https://www.literotica.com/s/bachelor-party-gang-bang
https://www.swinglifestyle.com/erotic_stories/cuckold/my-wife-helps-me-by-doing-a-bachelor-party/Storyid_58780/readstory.html
https://www.literotica.com/s/bachelor-party-surprise
- cant find stripper, gf takes place
https://www.literotica.com/s/bachelor-party-gone-wild
https://www.literotica.com/s/the-bachelor-party-3
https://www.literotica.com/s/the-brides-first-dance
- bf bachelorette, amiga gets her to pretend to be the stripper
- the masked-stripper is test-groped by friend to test bf fidelity
- beta resists and gives alfa the go to fuck her, unknowingly its his fiance, in their bed
  - later verbally humilliating her fiance, known only to the friend
** SURROGATE
http://darkwanderer.net/threads/surrogate-mother.7502/
https://www.literotica.com/s/an-affordable-insemination
- wife's sister is infertile and asks her to be impregnated by her husband
  - second part: https://www.literotica.com/s/an-affordable-insemination-redux
https://www.cuckoldsforum.com/index.php?threads/take-your-medicine-honey.6260/
- medicine keeps bf impotent, bf discovers he is cuck
- card game where non-numbers leave him caged
https://www.literotica.com/s/mutual-agreement :impotent:

** BBC DESCENT / BLACK
https://www.literotica.com/s/the-speedo-doesnt-lie-ch-01 :slowlysubmits:coachwife:
https://www.literotica.com/s/his-breeding-cow
https://www.literotica.com/s/family-disrupted-pt-01
- bizarre world, friend imprisoned and gorgeous wife already cheating
- gf is feminist but still gets attarted to bully, justifies him
- bully killed dad-son while fucked mother and daughter
- school director is antipatriarchy goddess
** OTHERS
https://www.literotica.com/s/allure-of-the-bad-boy
- goes to have public sex at night with bf, goes back to car for blankets but actually to get fucked by random sexy drug dealer while bf waiting in the woods
https://www.literotica.com/s/the-locker-bull
- to antibully sister and cheating gf: who is in locker?
https://www.literotica.com/s/all-in-my-head-ch-01 :jenny:scott:alice:threesomeneverforbf:
https://www.literotica.com/s/cuck-therapy-pt-01
- couple therapist gets them into it, after she cheated
==Every single story written by== [[https://www.literotica.com/stories/memberpage.php?uid=389201&page=submissions][J267]] [[https://www.literotica.com/stories/memberpage.php?uid=2556793&page=submissions][everyonesavoyeour]] [[https://www.literotica.com/stories/memberpage.php?uid=1029823&page=submissions][purplemonkeydishwash]] [[https://gustavjorgensonauthor.wordpress.com/][gustavjorgenson]] [[https://www.literotica.com/stories/memberpage.php?uid=918040&page=submissions][xleglover]]
** TOPICS
HOTWIFING
https://www.literotica.com/s/humiliated-1
- Jerk fucks wife in a party and everyone could hear
https://www.literotica.com/s/giving-nikki-away
- bf away, through cam bf gives in and witnesses gf become friend fucktoy
https://www.literotica.com/s/you-can-t-rewind-reality
- asian chinense wife for valentine gifts hubby his cuck fantasy
https://www.literotica.com/s/ill-be-your-woman
- husband pushed for it, went on vacation with alfa, once back she gives alfa husband-bed, stays married for the money
2 CUCKS
https://www.literotica.com/s/three-friends-two-cuckolds
- both know
https://www.literotica.com/s/flex-appeal
- black bodybuilder, 2 gfs cheat, never find out
https://www.literotica.com/s/innocent-girlfriend :virgin:
- alfa makes his-brother wife cheat on him, then uses this anecdote to get alfa-bff interested in letting gf experiment before marriage so she doesnt cheat on him
  - only finding out at the end that alfa was the cucker in the annecdote
  - two woman for alfa, both cucks like to see spectacle
DOMINATRIX
https://www.literotica.com/s/denial-ch-01
- wife gets bf into bdsm, later another domiatrix joins; later her mother
- sexless marriage
SISSY
https://www.literotica.com/s/getting-nailed-1
- almost accidentally they get into it, alfa didnt recognized bf
UNWANTED
https://www.literotica.com/s/ready-for-some-football
- alfa friend of friends makes wife his slut in front of them
- asks her to do things and she does, soda at tits
OBLIVIOUS CUCKOLD
http://www.obliviouscuckold.com/your-condoms-are-way-too-small-for-me-buddy/
- asks bf for a condom, turns out its too small
http://www.obliviouscuckold.com/my-girl-made-out-with-my-buddy-in-front-of-me-at-a-party/
- asks to lend gf, but she cucks her bf publicly and cruely
EMBRACED
- https://www.literotica.com/s/my-crush-dates-a-jerk
  - beta finds the love and eventually embraces her and his own(cuck) needs
  - wins her over slowly
  - they become the perfect couple
  - alfa flirts with her in front of party
REUNION
- https://www.literotica.com/s/ten-year-reunion-ch-01
  - school reunion, she meets her old bf, chance of swing with his hottest wife
    - they have a fuck date while beta a cute date
    - amiga gives lap to beta, who must not touch, while alfa fondles gf
- https://www.literotica.com/s/the-reunion-125
  - bf wakes up to gf getting banged after at school reunion makes the mistake of complaining-remembering it to old bully
    - while at it she finds gf ring and makes him propose to her
    - she pretends its a dream and bf wakes up to her acting as if nothing happened
TRUE EVIL
https://unrelentingcruelty.wordpress.com/category/single-episode-stories/evil-love/
- normal woman gets corrupted, job denial, kills bf while having sex with alfa
https://storieswithnebic.wordpress.com/2016/07/08/julias-descent/ :brainwash:bully:
* GAMES
** NTR
https://f95zone.to/tags/ntr/
https://ulmf.org/
https://ulmf.org/forums/hentai/?prefix_id=70
TRANSFORMATIONS also on:
https://tfgames.site/  or https://itch.io/c/1814648/tf-games


ntrge:
nebel geisterjager
dark hero party
ntr legend
The Adelaide Inn

interactive cuckold website



Scars of summer
https://store.steampowered.com/app/1405470/Scars_of_Summer/
Kedamono (Kazoku) tachi no Sumu Ie de ~Daikirai na Saitei Kazoku to Kanojo to no Netorare Doukyo Seikatsu
beta and crush seem to be warming up to a relationship only for him making the mistake of taking her home and there having her father and brother in law (who hate him) slowly corrupting her and take her away
- NAME

* LINK
https://sukebei.nyaa.si/view/2047859
Iro Yoridori
The first few hours of the game focus on the hottest guy in school fucking every girl around. He even fucks your crush, the class president!
All he does is peep on people having sex and jerk off afterwards. The good ending to the game is that you get the sloppy seconds of your childhood friend.
The three choices in the game only occur during the final hour of the story.
You have to watch five girls get seduced, fucked, and heartbroken before you ever get a choice. And there’s no way to protect your childhood friend from this either.
Most of the scenes involving your childhood friend require that you consciously pursue the bad ending.
Your childhood friend is a total cutie. You on the other hand, are a moron. She’s in love with you but you don’t get it. As a result, she fucks the hottest guy at school to get back at you.
- NAME

* LINK
https://hentaireviews.moe/2020/09/23/cuckolding-netorare-hentai-game-review-iro-yoridori/
NTR legend
your house is a mess! Your neighbors are pissed and they’ve had enough! The neighbor’s wife has agreed to clean up your place for a small payment. A sexy married bitch is coming over! You’ll be a complete gentleman, right?
You corrupt the neighbor’s wife and convince her to have sex on camera. Then you show it to her husband, who spirals into cuckold depression – he literally cries in his bedroom alone.
- NAME

* LINK
NTR LEGEND
https://hentaireviews.moe/2020/08/29/cheating-wife-hentai-game-review-ntr-legend/
https://imgur.com/a/UvCCWtp
https://f95zone.to/threads/ntr-legend-v1-4-20-goldenboy.58102/
https://mega.nz/file/CdAgHCaT#t19JsxuQ9KEIWNnUytOds5Qy-26blJ3y3PT176f2MWw
Taimanin Yukikaze 1 and 2, Iroyoridori, Marina's Cuckolding Report / Leanna's Slice of Life
[FEYADA] Knightly Passions
https://www.patreon.com/FEYADA
Dark Hero Party
https://store.steampowered.com/app/1015790/Dark_Hero_Party/
** NON NTR
- https://dikgames.com/
Operation Lovecraft: Fallen Doll
a multiplayer bestiality cuck simulator, lovecraft inspired
glamourous investigators as they battle cultists and eldritch horrors
https://store.steampowered.com/app/1685960/Operation_Lovecraft_Fallen_Doll/
Berserk
Casca corruption by the demon Femto(Griffith), while Guts (her love) gets ripped to shreds
The Atelier Ryza games
three childood friends: Ryza the alchemist and protagonist, Tao who is extremely beta (yellow hair), and Lent the hunk (cucked Tao), who is in turn cucked by his abussive dad Samuel
- Samuel thinks Ryza looks just like her sons mother
- After the first game everybody but Ryza went on a three year adventure, leaving her at her hometown with Samuel to fuck
- her hips widened in those three years, implying she gave birth
Scarlet_Maiden
you must repent(get spanked) in order to unlock new abilities with your accumulated sin
https://store.steampowered.com/app/1968840/Scarlet_Maiden/
Riginetta's Adventure
pixel island survival
https://f95zone.to/threads/rignettas-adventure-final-supermicankurafutobiiru-mutokoro.53186/
https://twitter.com/super_mican
Milky Quest
pixel art rpg
https://f95zone.to/threads/milky-quest-bluelab.4498/
AI shoujo
- 3d crafting, ark survival
- https://wiki.anime-sharing.com/hgames/index.php?title=AI_Syoujyo
- https://store.steampowered.com/app/1250650/AIShoujoAI/
* NTR SITES
- Vixen
- HotwifeXXX
- https://fetlife.com/ social-site
- Touch My Wife
- New Sensations
- https://bull.one/ chat-simulator
- https://www.literotica.com
  - https://www.sexstories.com
    - https://www.sexstories.com/themes/114/Cuckold/s-date
  - https://www.lushstories.com
  - http://www.asstr.org/
    - https://asstr.xyz/
  - http://darkwanderer.net
  - https://gustavjorgensonauthor.wordpress.com
  - https://nsfw-story.com/tag/cuckold/
    - https://nsfw-story.com/?s=cuckold+daughter
  - https://archiveofourown.org/works/search?work_search%5Bquery%5D=netorare
    - cheating/adultery/netorare/cuckold
- bdsmlr.com
- https://worshipher.org/resources/ (apps and pocasts)
** INTERACTIVE STORIES
https://www.asstr.org/%7EArthur_Saxon/Alyssa.html#0
https://hyperdreams.com/
https://bull.one/
 https://lewdalchemist.games/

 - https://chyoa.com/story/Can%27t-we-let-him-stay.54001
  - https://chyoa.com/story/Arousing-Suspicions.36787
https://chyoa.com/story/Karen%27s-Secret.14651
https://chyoa.com/story/How-many-of-your-friends-do-you-think-would-fuck-me.13739
https://chyoa.com/story/
** CAPTIONS CUCK
https://www.reddit.com/r/netorare/comments/sc6sne/ultimate_netorare_list/
https://xxxredd.it/hotwifekatrina-gifs
https://www.cuckart.com/ quick cuck-hotwife drawings with captions
u/nubsimp
u/TUGALISBOA1996
tab109 (patreon)
lewdtuations / redgifs (cuck captions)
[[https://www.reddit.com/user/chant9][u/chant9]]
u/Cariporn
[[https://www.reddit.com/user/Automatic-Interview][u/Automatic-Interview]]
u/Dogtanian69
[[https://www.reddit.com/user/PervertKinks][u/PervertKinks]]
[[https://www.reddit.com/user/Apprehensive_Cup_7][u/Apprehensive_Cup_7]] (never letting out, cuck honeymoon)
u/2accountsbanned1996
https://www.obliviouscuckold.com/
http://www.kinkyquotes.com/
- podcast: https://venuscuckoldress.com/
  - https://mobile.twitter.com/cuckoldressv
BDSMLR
https://alices-adventures-in-femdom.bdsmlr.com/
https://cuckcuckgoose2.bdsmlr.com/
https://keephimcaged.bdsmlr.com/
https://2lf.bdsmlr.com (interracial)
https://thecagestore.bdsmlr.com
https://hottiewives.bdsmlr.com/
https://imawannabecuck.bdsmlr.com
https://cuckyblog.bdsmlr.com
https://mstara.bdsmlr.com
https://corneador-cornudo.bdsmlr.com/ (spanish)
https://unfortunatedesires.bdsmlr.com/
https://htwfsixfap.bdsmlr.com/
https://baristapimps.bdsmlr.com (interracial)
https://manversuscuck.bdsmlr.com/ (bbc)
https://bellexxxa.bdsmlr.com/
https://dogtanian69.bdsmlr.com (feminist)
https://miscellaneouscaps.bdsmlr.com/
- https://miscellaneouscaps.bdsmlr.com/search/cuckold%20dating
REDGIFS
- lewdtuations
- randompervertguy
- ntrcaptions
- hot captions
- PrincessBlowMe
TWITTER
twitter@slash_soft (3d hentai)
https://twitter.com/hfhwtwit/ (helplessforhotwife)
https://twitter.com/PrettyPinkPower (once got paid 1000)
https://twitter.com/CuckWinters
 https://www.patreon.com/winterscuck
https://www.patreon.com/obeywomen
*BLACK
https://twitter.com/Linecypt
https://twitter.com/waifus4bnwo
https://twitter.com/buIIyqueen (cool loser caption) Meiji
https://twitter.com/FaunQoS
* SUBREDDITS
** NTR SUBREDDITS
- Cuckold
- cuckoldcaptions
- cuckoldstories
- CuckoldPregnancy
- CuckoldPsychology
- cuckold
- happycuckold
- cuckhumiliation
- cuck
- caption_king_nsfw
- CuckoldComics
- [[DENIAL]]
HENTAI NTR
- [[HENTAI OTHER]]
- netorare
  - ntrs
  - hentainetorare
- hentaichastity
- hentaicaptions
- FemdomHentaiCaptions
- HentaiRiding
- HentaiBlackedCaptions
- SissyHentaiCaptions
- HentaiAndRoleplayy
OTHERS PESPECTIVES
- bangmybully
- HotwifeCaption
- slutwife
- Pregnant_Hotwife
- hotwife
- BrotherCucker
- IncestCuckCaptions
RELATED
- HeStoleMyGirl
- thepointofnoreturn
- snapcaps
- xxxcaptions
- hotpastCaptions
- Captionned_Sluts
CHEATING
- Not_Cheating
- CheatingSluts
- CheatingCaptions
- cheatingwives
- stupidslutclub
- SluttyConfessions
** NON-NTR
- pigtails
- gonewild
- Oilporn
- girlskissing
- lactation
  - [[https://www.reddit.com/r/MilkyMILFs/][MilkyMILFs]]
- BreastEnvy       (huge vs small tits girls)
- girlskissing
- ShimaidonHentai :twosisters:
- photo of phone with photo in public, of her having sex https://www.reddit.com/r/publicreminders/
SHAPE
- Adorableporn
  - adorableporn
  - SmallCutie
- legalteens
- goddesses
- BreedingMaterial
- bustypetite
- ghostnipples
- Sextrophies
- BigBoobsGW
*TATTOO
- tattoogirlmodels
- tattoogirls
- tattooed_girls
INCEST
- myhotsister
FEMDOM
- Fantastical_Femdom
- bdsmgw
- politicalfemdom
- BallBusting
- Femdom
- femdomgonewild
- petplay
- HumiliationCaptions
- femdomcaptions
*DENIAL
- [[NTR SUBREDDITS]]
- Censoredforbetas
- [[https://www.reddit.com/r/Virgin_Humiliation/][Virgin_Humiliation]]
- virgin_humilliation
- teaseonly
- Tease_Denial_Captions
- smalldickhumiliation
- keyholdercaptions (fav)
- pussyfreeporn
- femdomdenial
**CHASTITY
- chastity
- ChastityCouples
- ChastityCuckolding
- ChastityCuckolds
- ChastityCaps
- chastitychoice (fav)
*INTERRACIAL
- [[HENTAI OTHER]]
- asiansgonewild
- hentai_interracial
- BNWO2050
- BlackWorldOrder
- ircuckold
- QueenofSpades
- AsianHotties
- BlackWorldOrder
- IrBreedingPregnancy
- TheBlackedDominion
- [[https://www.reddit.com/r/damngoodinterracial/][damngoodinterracial]]
CLOTHES
- OnOff :clothes:
- skirtnoshirt
- kneehighsocks
- cuteasfuckbutclothed
- croptopgirls
- 2busty2hide (cant hide)
  - overflowingtits
- nsfwoutfits
*THIN FABRIC
- tightdresses
- seethru (sheer erotica)
- ThinClothing
- pokies
  - nobra
  - braless
- sheer :lingerine:
*ITEMS
- piercednipples
- nipplepiercings
- collared
- bondage
- justthejewels (jewery, cosplay, chains)
*THEMED
- SundressesGoneWild
- schoolgirlsgonewild
- suicidegirls
- HotInTheKitchen
**SHINY
- latexcosplay
- ShinyPorn :latex:
- GloveLove :latex:
**COSPLAY
- CosplayLewd
- cosplaygirls
- cosplaybabes
- CosplayNation
**GOTH
- bigtiddygothgf
- gothsluts
WORK
- officelady (hentai)
- carandgirls (automovile)
- Secretary
- workgonewild
- hotofficegirls
HENTAI OTHER
- [[HENTAI NTR]] [[INTERRACIAL]]
- SportsHentai
- CuddlesAndHentai
- araara
- pixelartNSFW
- [[https://www.reddit.com/r/GloryHo/][GloryHo]]
- corruptionhentai
- blackedart
- animebodysuits
- [[https://www.reddit.com/r/pinx/][pinx]]
- hentaicaptions
- wombtattoos (hentai)
  - hentaislutmarks
- ecchi
- SFMCompileClub  (hentai 3d)
- monstergirl (hentai)
- ElegantR34 (hentai)
  - OfficialSenpaiHeat
- BigAnimeTiddies
*DOMINATION
- hentaifemdom
  - [[https://www.reddit.com/r/HemdomBlog/][HemdomBlog]]
  - HentaiLesdom
- [[https://www.reddit.com/r/hentaibondage/][hentaibondage]]
- CumCleanCaptions
- pegginghentai
- Echhibondage
- [[https://www.reddit.com/r/Tentai/][Tentai]] tentacle hentai
- [[https://www.reddit.com/r/HookedUpHentai/top/?t=year][HookedUpHentai]] (chair, mecha bondage machine)
*ZOO
- hentaibeast (zoo)
- https://animopron.com/my-released-videos/
- https://www.naughtymachinima.com/
**REAL
***NEW
- https://femefun.com
  - [[https://femefun.com/videos/48987/xxx-bestiality-bitch-doesn-t-resist-and-relaxes-being-penetrated-by-dog/][vid1]] [[https://femefun.com/videos/49485/anonymous-girl-doesn-t-mind-if-xxx-dog-cums-in-pussy-after-fuck/][vid2]] [[https://femefun.com/videos/54620/a-slave-exhibitionist-to-get-fucked-by-her-dog-in-the-car-for-money/][vid3]]
- https://area51.porn/tags/dog/
- https://bestiality.zone
  - [[https://bestiality.zone/video/cathartic-a-important-quantity-of-gamete-from-my-pussyhole/][vid1]]
- https://boarporn.com/
  - [[https://boarporn.com/video/the-pretty/][vid1]]
***OLDISH ONES
- [[https://zooporn.stream/video/her-nipples-and-her-well-shaven-pussy-may-simply-be/][first video]]
- https://katitube.com
- https://beastiegals.com
  - [[https://beastiegals.com/1716324.html][vid1]]
* FAV ACTRESSES
** Sabrina Nichole
reddit@Sabrina_Nichole
when younger was browner, dark eyes fake blonde, big tits, squary jaw
Ryuko Matoi Cosplay - https://m.imgur.com/a/b2nfz
** Firstbornunicorn :fav:
pink hair white aureolas
same girl that used a tiger eyes-mask, and tail as butplug, fucking in the kitchen
twitter@camgirlunicorn
https://namethatporn.com/pornstars/firtsbornunicorn.html
** ellesclub :fav:
twitter@ellesclubxoxo
instagram@trashy.waifu.club
girl that deceived pornhub about her age, black hair (colored soft pink), blue eyes, fake tits
cicada tattoo at her chest
always in a state of sadness/hornyness
mesh-net like cloths, or tight sweaters
** bella_rose1999
reddit@bella_rose1999
went to onlyfans never to return
in bed, nips half-covered by bracier, maquillaje finito, actually fat
https://www.webcamshows.org/videos/bella_rose1999-chaturbate-webcamshow-02-09-2020-03-18/
https://rec-tube.com/watch/2020090702420343/?__cf_chl_managed_tk__=93139d1c4099822e1c85710bbed26efb34ece088-1624043389-0-AUJUjBD0tRiYwnEwUvNdl0cMQH2WDkKQZVVhcH46qCNeZie8iBIoGiTEftfzPAOUucs45ArLTouwsVASD5C8ApIWET-WIwn1ObBUKVpqa8epfdxqvCTjomF0a1owegXmw1AW7NPM8aQCIu33bYYxkt3XV4b8ZFpLC-DqTyZKOEv9kWOtrIgAew4hG2WmKYyiA91b4dxvceG2T97DxxwFgELanBPOVPU36uJ67zoNDddJ5oRyHdLy2ArmAK4lHV8Lz9N32Ei8nnYUbbLc-De1Gjk8DXnvzx563zNbpbKuYHojTI7MO7ZrYlCJBj7Doy-tO-dboFEFBBmHZua4y558aQYe5-xPJfzMj_F6qkfg9xku9dqZ_BU8d5Bg31SE4eqhxg7VVO1aRuDfV0ZKTn3KgxMGlSFaZ-NDpFA4hhgPT4f8bbn7c8peOlxhfvdLszWESKBwLMNihGNWxaIL-0dcDr_5Gw_2QTeYWNjpRtnRhkE3sXXQBOfefuUNcm_sHM1I0PdHXaC30XJkP7fvKca7kRNUOI0uJ1HkdfF6_qHJutZzloK-H0PJevFEG0nC4iYKGQzikYZ1R6tvE1IvyfzImDSBbrfEWX9hJdMTMoG-7gXNhbRcpumHtiCvRCqebSzG6eRdrVTSB-8pGYoF8TJe1bk
** kalie kittie
twitter@infatuagedkitty
colegiala transparent top with heavy hair, milky skin, small skull
** Calisha Maja
tallest blond, long neck, literally perfect
https://www.xvideos.com/models/carisha-maja#
** Lily Constatine
onlyfans@lily_constatine
morena, blond extensions, (black top, browny bottom, beige skirt), sat on a chair
** Helly Valentine
cosplay model, wide skull, purple hair
instagram@disharmonica
** mikomi hokina :fav:
raphtalia, 2B cosplay, milky skin, black hair
office slut passing by in black tight dress
twitter@MikomiHokina
instagram@mikomihokina
** Enji Night
instagram@enjinight
cosplay, 18, red dominatrix, lara croft, 2B, tifa
white top pink tshirt
** sara calixto
moon tatoo in the cleavage, latina, mesh-net cloths
coralinne Suicide
onlyfans@saracalixtocr
twitter@saracalixtocr
** Miyu :fav:
barbie tier girl, cosplay: hange (attack of titans), riasgremory,
perfect lips, artifical big eyelids
huge but secret tits
instagram@miyu_ameya
tiktok@miyu_ameya
** indigowhitecosplay
twitter@indigowhitecosplay
also https://twitter.com/npcprincess666
christian nun cosplay
princess setting, cutting up her skirt, expelled from tiktok, pornhub pink top, fake blonde, often pink
https://www.pornhub.com/video/search?search=indigo+white+cosplay
https://www.redtube.com/39382091
https://www.youtube.com/@IndigoWhite/videos
** Vita Celestine
colombian streamer, bed kiss, brown hair sometimes puplepinkred
twitter@vitacelestine
instagram@vitacelestine_
https://porngao.net/vita-celestine-dildo-and-vibrator-masturbation/
** San Chan Claudia
got called a puta and got angry, cosplay progresively whorish, square back but curvy
sanchanclaudia (cosplayputa finita)
** Mae Peach
pawg, heart shaped necklace, black hair often redish or puple, purple eye makeup/shadows, found in r/bigtiddygothgf
reddit@maepeachx
** Cristy Ren :fav:
tanned skinned, latina?, huge tits
twitter@cristyren
https://networthandsalary.com/christy-ren/#Christy_Ren_Single_or_Dating
fake tits: https://rpclip.com/video/103593/
Mary Nabokova
just like Cristy Ren
instagram@mary.nabokova
** Shevchenko Dasha
instagram@_da.shev_
classy, arm tattoo, short brown hair, barbie face, white cotton shirt
** Melissa Debling :fav:
instagram@melissadebling
twitter@MelissaD89
tanned brit phenotype, fake blonde, fake tits tho
going out of cuckshed half dressed
** Helga Lovekaty
twitter|instagram@helga_model
femenine tanned dark haired, quality cloths or lingerine, mole in the jaw
** liya silver
OTHER NAME: Kristina Shcherbinina
tatoo below tits fucks blacks
twitter@LiyaSilver
https://www.pornhub.com/pornstar/liya-silver
** Giselle Montes
twitter@GiselleMontes18
small and thick, friend of Mia Marin, fake blonde, fake tits, whiteish
grooped in front of oxxo,
** Mia Marin
long and thin, frined of Giselle Montes, dark hair
transparecy, white cotton shirt in the subway
twitter@MiaMarinOficial
** Miroslava
nude in front of UNAM and above highway bridge, swinger couple, never shows face, tanned, small pierced tits
twitter@mirosyarte
** DanielleSharp
greeting her cucked(by accident) boyfriend with fucked look
blonde extensions, darkhaired, blue eyes, two ponytails/pigtails
instagram@danielleksharp
** SarahRoseMcDaniel :fav:
instagram@SarahRoseMcDaniel
eyes different colors: blue & brown/green
** Denisse Gomez
tanned venezolana, dark haired
using black top-transparency and tigth purplish shorts walking in the street
instagram@denisse._gomez
https://www.pornhub.com/pornstar/denisse-gomez
https://www.xvideos.com/video17214345/vl_720_932k_55840311
** gothegg
bigtittygothegg
instagram@gotheggofficial
tiktok@goth.egg
greenhair, bups at camera while hopping, butter face
https://www.pornhub.com/view_video.php?viewkey=ph5f53c36db4c77
** brooklyn chase
classy slut, brown haired, fake blonde
masturbates/sucks alfa while bf at phone, cheating porn
https://www.xvideos.com/pornstar-channels/brooklyn-chase-1#
** Katerina Soria :fav:
instagram@katerina.soria
r/KaterinaSoria
office classy slut of the highest quality, very femenine, light brown hair, blue eyes, big tits, usually with tights/knee socks
** Evie Rain
happa china/cambodia, goth style often, found in asiansgonewild reddit, cosplay
twitter/reddit@xcorpsekittenx
** Amanda Elise Lee
fit, got pregnant, blonde, expensive slut, usually in excersice top
instagram@amandaeliselee
** Vyvan Le :fav:
instagram@vyvan.le
asian, fine girl, soft pink hair, sometimes in corset, girly clothing
** katerina hartlova :fav:
got pregnant, blonde, huge tits
bike girl, mechanic girl, farm girl,
twitter@Katy_Hartlova
** Marta E
ucranian, white nips / aureolas blancas
twitter@martae569
** Chanel Uzi
southeast asian, tanned, short brown hair, transparencies
instagram@chanel.uzi
instagram@chaneluziofficial
** Miss Alisandra :fav:
captions-microgifs dominatrix/denial for onlyfans, red haired often, big earrings
twitter@missalisandra
** Rachel Cook :fav:
fine long girl, small tits and still fake, curvy brown hair, blue eyes, thin jaw
mechanic cloths
twitter@rachelc00k
** Niece Waidhofer :fav:
black hair, square jaw, thin waist, milky skin, blue eyes, black eye makeup, inhouse garden, sandia collected
instagram@niecewaidhofer
** MaddymayeBoutine
reddit@MaddymayeBoutine
fake blonde, only ever using swimsuites
** Ava Addams
THE milf, curvy brown hair, huge tits
twitter@avaaddams
https://www.xvideos.com/pornstars/ava-addams#
** Elsie Hewitt
https://www.instagram.com/p/B1Hx4sJBlrq/
instagram@elsie
browwn hair fake blond, hippie/nerdish face
THE photo in white swimsuit near the pool
** Katerina Monroe Kozlova
reddit@katerinaKozlova
twitter@katru.kozlova
Teen Monroe
soviet flag holding girl, sometimes nude, performing sex/lewd movements, blonde, either short hair or two ponytails / pigtails
lesbian couple
** Velvet Valerina
tiktok@velvetvalerina
tiktok@velvetvalie
tanned latina, short purple hair, lewd dressed and dancing, cosplay as maid
** Niley Hott :fav:
tanned latina streamer: milking herself, wetting her cloths with her milk, dark nips
THE milking
https://www.xvideos.com/video25658181/niley_hott
reddit@NileyHott
twitter@nileyhott
** Xev Bellringer
THE sex roleyplay
blonde, blue eyes, big tits, shares hubby with her unicorn friend
twitter@OfficialXev
** Stacey Poole
tanned british
https://www.pornhub.com/pornstar/stacey-poole
twitter@StaceyPoole1
** Vica Kerekes
red head, red dress, playing billiards, takes her underware to tight her hair
Men in Hope - movie
** GabbieCarter :fav:
instagram@gabbie.carter
twitter@gabbiecarter00
brown hair, fake blond, blue eyes, wide face, huge tits, usually in sundress, in Wheel of Fortune
** Remy LaCroix
twitter@Remymeow
light brown haired, small tits wide hips, dancer with rings, fucks blacks
** Jada Stevens
friend of Remy Lacroix, dark haired, small tits, lately fake blonde, sometimes hair in braids
twitter@jadastevens420
** Riley Reid
porn twin of Remy LaCroix
light brown curly hair, chinesse/japanese tattoos in the back (lemonade meaning), fucks blacks, cuck porn
twitter@rileyreidx3
instagram@LetRileyLive
** Angela White
dark haired, blue eyes, huge tits
selfie walking with bouncing tits while in lingerine, fucks blacks
twitter@angelawhite
** Alexa Pearl
criticism of tit augmentation, brown hair, big earrings
reddit@alexapearl
** Amouranth
actually millionare married to chinese billionaere
lingerine/cloth selfies
brown hair often red, blue eyes
reddit@Amouranth
** Octokuro :fav:
purple hair (sometimes soft blond/pink), fake tits, purple latex, often neon colors/theme,
instagram@octokuro.model
** KagneyLinnKarter :fav:
THE photo of nude bondage girl with blue tape in mouth
blonde, blue eyes, big tits, fucks blacks, cuck humilliation
twitter@kagneythebabe
** SashaFoxx
THE blowjob master, often does denial ala dominatrix, brown hair blonde extensions
** Bonnie Rotten :fav:
spiderweb tatto on tits, tattos in her whole body, dark haired sometimes blonde, tanned
Pee porn
reddit@BonnieRotten
** Janice Griffith
reddit@janicegriffith
brown latina with brown hair, once tainted purple or blue, often blonde
THE fucked in oily massage table scene
** STPeach
blonde, swatted to get big ass
married asian guy but was not actually attracted to him, often does lewd or confesses things without realising
twitch@stpeach
** LarkinLoveXXX
sick of her skin, white milky skin, dark haired, complex tattoo in whole belly
THE purple haired lewd movements
oil solo porn, ahegao eyes
https://www.pornhub.com/view_video.php?viewkey=ph5d49ac90eff25
https://www.xvideos.com/video12518309/hot_pov_bj_408
https://www.xvideos.com/video19454579/punk_girl_plays_with_tits
** LaylaLondon :fav:
tanned british, extensions of lighter brown hair, ugly tatto in belly side
cuck captions her in sweater: alfa will punish
reddit@laylalondon
** Codi Vore
reddit@CodiVore
pawg, blond, blue eyes, huge tits, nedy face, cowgirl
shower tits-on-glass porn, fucks blacks mostly
** Brooke Wylde
reddit@BrookeWylde
butter-nerdy face, big tits, light brown hair
fucking while her mother on the phone
Stella Cox
favourite, whites-milky skin, brown hair
often dressed as secretary (cosplay)
twitter@thestellacox
reddit@StellaCox
** MaitlandWard
reddit@MaitlandWard2
redhead, blue eyes, heavy hair, big tits, fucks blacks mostly
in tight sweater holding punpkin photo
unironically cucked her IRL husband, spends non work-time away with her black coworkers
** Kendra Sunderland
twitter@KSLibrayGirl
blonde, banned from instagram (affair with CEO joke) and TikTok
"masturbation in library" her first porn video
https://www.xvideos.com/video59756613/kendra_sunderland_full_library_video
left her IRL bf because he asked her to not do black-interracial-porn only
** Amber Blank :fav:
blonde, natural tits, only does black interracial porn
IRL cuck bf/husband who records her
https://www.tnaflix.com/amateur-porn/Amber-Blank-With-Her-Bf-And-Her-Black-Bull/video4672426
https://www.xnxx.com/video-3wa0vda/amber_blank_destroyed_by_bbc
https://www.xnxx.com/video-giz7l31/amber_blank_bbc
** YogaHotwife :fav:
black haired, small tits, husband in chastity who records her, muscular black bull
THE photo where she compares black cock vs cuck
disappeared because some asshole doxed them and decided to slut-shame Jen to her family
https://swingerpornfun.com/2019/08/06/yogahotwife-riding-bulls-cock-while-describing-to-hubby/
https://www.xvideos.com/video31284781/hot_wife_cuckolding_her_hubby_with_a_bbc
https://spankbang.com/5jd85/video/yoga+hot+wife+complete
** BBCSlutWife4U2 :fav:
reddit@BBCSlutWife4U2
teacher got doxed and fired at school, was recording her material in the school bathrooms
artificial tits, mesh-net lingerine, bbc-owned tattoo in her pubic region
** Jessica Davies
gif blonde pink/black bra lingerie shaking
https://www.reddit.com/r/goddesses/comments/2igq9f/jessica_davies_gif/
reddit@Jessica_Davies
** Piper Blush
reddit@piperblushreddit
slave collar, permanent iron collar
youtuber and porn actress, always records her doing slutty things from lewd angles
french speaking canadian
https://www.xvideos.com/models/piper-blush#
** Aniuta Mini
tiktok@aniuta_mini
female with nice body parading herself driving her motorcycle around
black haired, leather tight clothes
** Arietta Adams
https://www.pornhub.com/view_video.php?viewkey=ph5ed8233c661e9
(fake) redhead, light brown hair, fucks blacks, very messy(fluids) sex
twitter@AriettaAdamsXxx
** Sukiayuzawa
instagram/twitter/reddit@sukiayuzawa
tifa cosplay, asian, jaw operated?, flat face, and also fake small tits, but cute
** Princess Sabrina
reddit@princess_sabrina_xo
twitter@Bratty_Sabrina
brown hair, often pink or blonde
ballbuster, has smaller and thinnier bf, she lets him fondle her up only to suddenly kick him in the balls
after kicking him, he likes to dance over his defeated corpse
** Mistress Elise
fake redhead, ballbuster / femdom, but what she actually did is twist the testicles
is the one domme that IRL interviewed one of her victims who she had sent to the hospital due to accidental permanent damage, he spent 10 days there and they had to drain his nut sack and she just laught it off
** Bunny Ayummi :fav:
twitter@BunnyAyu
instagram@bunnyayumi
streamer, pawg / cow like, shot hair, fake blonde (dark hair), huge tits, nerdish vibe
tight sweater-(dresses|bodysuits), clothes showcase, sometimes cosplay, cowgirl, sugoi dekai
** Moldy Locks
antifa girl, blonde and thin, hippy tier
feminist corruption, turns out she made slut/lingerine photos (mesh-net) and had fisting pornhub videos, got punched
** Hime Tsu :fav:
twitter@hime_tsu
japanese? (probably white pretending to be asian), porcelan skinned, thin waist wide hips medium tits, pink aureolas, probably brown haired
never shows face, self identifies as bisexual
likes to wear leg harnesses, dresses girly with ocational riot gear
THE faceless girl
could be 35+ years old?
** Victoria Riaz
twitter@VictoriaRiaz
instagram@victoriariaz_
tattoed arms, latina slut, big tits
** Julia Zuzu
reddit@julia_zuzu
morena 30+, brown haired with blonde, barbie tier
often sundresses, dressed as colegiala
** Kim Cockerspaniel
instagram@kimcockerspaniel
THE small skull girl, asian, tall
https://www.reddit.com/r/goddesses/comments/kn5fjx/
r/KimCockerspaniel
** May Marmalade
cat girl, red head, camgirl
her cat often was in the shot
cancelled for throwing away her cat (no harm)
https://www.xnxx.com/pornstar/may-marmalade-1
** Samantha Jay
Samantha Janecki
shyloh
twitter@njvanity
light brown haired, blue eyed, nerd, see through, worked at hooters
https://imgur.com/gallery/fW48r
https://twitter.com/samanthajanecki/
https://www.pinterest.com/njvanity/_saved/
https://64.media.tumblr.com/51846490b16aee22ab4d9d20ba005bb4/tumblr_nca2djDm0S1swmuzno1_500.jpg
** Emily Elizabeth
brown hair with blond extensions, barbie face, tanned anglo
twitter@emmilyelizabethh
reddit@emily_elizabeth
** Jennifer Love Hewitt
instagram@jenniferlovehewitt
thin, light brown haired,
from the show where she could see the ghosts, also from criminal minds, pigtails / two ponytails
** Violet Summers
twitter@violetsummerss
instagram@violetsummers.tv
brown haired, tanned skin, latina, green eyes (light brown eyes)
tight lewd cloths, often crop-tops
** Bonnie Lass
reddit@Bonnie_Lass
collared girl (black with letters), sometimes harness & chained, porcelan skin, never shows the eyes, blond
got pregnant at 38 years
** Estephania Ha
instagram@estephania_ha
artificial tits, pokies since tight clothes and no bra, brown hair, latina?, sand skin
** Miss Dawson
reddit@Hotmilf_Rose
41 years, divorsed, pokies, brown haired, glasses, broken hair
** Alisa Amore
thin long neck, brown hair, blue eyes, sundresses, nude holding flowers or crown of flowers as if where a bride
twitter@AlisaAmore
** Mia Khalifa
twitter@miakhalifa
lebanese, almond skinned,
muslim pink hijab porn, got threatened, got recruited when buying a hamburger
has a swedish husband
** Bryci
dark haired, cow like / cowgirl, pawg, lingerine bodysuit showcase, big tits
canadian, has a husband who is the cameraman; streams interviews
tbh aged horribly
@Bryci
** Chanel Preston
twitter@ChanelPreston
brown haired, big tits
all kinds of porn, yellow dress
** Sephine Lucicia
from the "sisters of battle (adepta sororitas)" of 40k, blue eyed grey haired
corrupted by Miriael Sabathiel, who was corrupted by slanesh
 https://www.deviantart.com/yangzheyy/art/lure-689989598
** Ekaterina Novikova
twitter@killer_katrin⁠
playing tennis, white shirt, leaned over net
** AliceCalli
reddit@AliceCalli
canadian milf, fake blond, blue eyed, natual tits, amateur
** Madison Kate :fav:
redhead, clowny makeup, hot red lipstick, red lingerine (the theme)
instagram@madi.kat
** Jadeyanh
instagram@ja.dey
twitch@vylerria
maid cosplay, paniter-artist wannabe
unironically blamed sexist men for her lifelong sexualized selfies
** Ekaterina Enokaeva
blonde, blue eyed
half nude librarian cosplay (her theme)
instagram@enokaeva
** Tessa Flower
reddit@TessaFlower
twitter@Tessa__Fowler__
brown haried, cowgirl, cow tier, pawg, huge tits
bounces/flexes her way into nudety
** Tanya Bahtina
Tanya Bahtin
soft tanned, russian?, tattooed arms and belly
used-and-disposed life vibe; thousand cocks stare
instagram@tanya.bahtina
** Emily Kimchi
Emi
tiktok@ph1girl
tiktok@konemita
half black half mexican, anime tier black girl, anime entusiast nagatoro cosplay
dancing black girl with deep pink colored hair
** Alice White
tiktok@alicewhite.xo
tiktok@alicewhitexoxoxo
onlyfans@aliceoncam
short red hair, glasses, lesbian?
girl running on high heels, balancer/flexible girl
getting foxy butplug inside her in public
red light only siluete slut dancing with acrobatics
** bunnie3png
onlyfans@bunnie3png
cow like girl, cowgirl, huge tits, cow cosplay, pawg
https://forum.sexy-egirls.com/threads/bunni3-png.97961/#post-676802
BBC GIRL
- lavenderthief
https://forum.sexy-egirls.com/threads/lavenderthief-blue.130722/
** carleyloakley
tiktok@carleyloakley
brown haired thin girl, somewhat tanned, blue eyed
iconic for dancing with her grid-pattern yellowish secretary suit, yellow top, white knee socks
obsessed with black lives matter (blm)
** Alizee Jacotey
Alice Lyonnet
alice
instagram@alizeeofficiel
tanned french girl, brown hair, singer, dancer; knee socks
tattoed at her back
https://www.youtube.com/watch?v=Q6omsDyFNlk
** Lauren Findley
instagram@laurenlf
fit girl, abs and powerful legs, redhead, tight sports clothes
** Melody Marks
Pricess Melody
fake blonde/black hair, actually brown;  nerdish, shy, pink nipples, fully natural not even tattoes
looks inocent as fuck, went to japan; unironically pro slut
twitter@melodymarksxxx
instagram@melbabiexx
reddit@MelodyMarks
** Lana Rhoades
fucks blacks, blue eyes, brown hair, clear nipples
girl drinking orange juice photo, cheated on her bf with former porn coworker
instagram@lanarhoades
** Ruby Alexia
black hair, blue eyes, some tattoos at arms/legs, earrings, nosering, milk skin, big tits
suicide girl, sometimes goth theme and black lipstick,
instagram@ruby.alexia
** Giulia Valeriani
instagram@moonchild_77
fit, excersice, fat when younger, blue eyes, brown hair
cosplay, her fav is 18, latex harness
** Codi Vore
reddit@codivore
twitter@Codi_Vore
THE cowgirl, cow girl, pawg
cute face, huge tits, brow hair
** Amy Murr
instagram@amy_murrr
twitter@Amy_Murrr
chaturbate@amy_murr
https://recurbate.com/performer/amy_murr/?page=1
https://www.camarchive.tv/model/amy_murr
thin petite girl, black hair, cat girl, tight crop top, slut collar, anime themed bedroom, saggy tits but still nice
camwhore, lesbian performances, often solo, french accent
wets her crop top (transparency), cat girl maid cosplay
** Cadey Mercury
short brown hair
fucks while cuck on the phone, several scenes, "multitasking"
https://www.redgifs.com/watch/arcticlegitimateisopod
** Emylia Argan
short haired, natural curly brown but often tainted darker, hippster glasses, Czech
fucking on the stairs
twitter@Emylia_Argan
** Astasiadream
thin cute face, dark eyes dark hair, princess feel
rezero-emilia angel, hinata, darling cosplay
darling cosplay where she pouches and her fingers touch
reddit@AstasiaDream
instagram@astaisadream
** Azami
twitter@Azami_1110
nice use of plastic, big tits, shiny oil and leather porn, succubus tattoo
mash cosplay the best
** Brianna Marie Dale
instagram@bdale22
looks like daniela, naturally brown haired, thick, cow, big tits
tongue piercing, barista, tape on aureolas or small bikinis
** Josephine Jackson
lesbian interracial, aesthetic on heels
brown haired, fake tits
twitter@josephinejxxx
** TinyFae
very nice legs, always wih a covid-mask, usually as as schoolgirl with crop-top in high-heels, pluffy room, black eyed and black haired
instagram@lil.trama.doll
reddit@tinyfae
twitter@fae_tiny
** LyzMania
reddit@LyzMania
onlyfans@LyzMania
pink haired petite, stockings and nice heels, nice big hat
small tits, pink nipples, milky skin
skin jewelry (with glue)
** Adelalinka Twins
( ADELINA | ALINA ) Fakhteeva
instagram@adelalinka_life
twitter@AdelalinkaJ
incest lesbian twins(sisters)
tanned, brownhaired
"looking for a wealthy husband to share"
Marcela Sisters
- Sisters Jade and Nyomi Marcela (asian)
- sister incest
** fairy :fav:
instagram@fairyanaaa
instagram@fairyalexx
two asian twins sistes
** Eunji Pyo
twitter@EunjiPyoapple
instagram@pyoapple
twitter@pyoapple
youtube@표은지Eunji Pyoapple
asian/korean, medium tits, maid cosplay
camwhore vlogs
** Mayy
reddit@Mayyy_22
younger Melissa Debling, british butter face
fake redhead (brown), thick eyebrow
THE girl taking a bath
** Richelle Quincy K
greatest ass shaker in the world
small loose yellow top, small shorts, bodypaint tattoos, dark eyes and hair
allegadly squirts like a fire truck
instagram@richellequincyk
https://youtu.be/wSuZ6ARlbpw
** Ivy Snow
tattoos hidden below clothes, Ear stretching
masturbating at boat, uncovering tattoo to to-be hubby
twitter@missivysnow
twitter@MissIvyJean
** Anastasia Cebulska
innocent face, milk skin, light brown haired, gray eyes
instagram@theanastasiah
** Julia Thompson
tiktok@juliathompson24
twerks to anoy her daughter, three sons
thin and slut, gammer
you get race loyalists who breed, but they are all cheating hypersexual sluts
** ShyLily
delicious voice vtuber
** girl_dm_
delicious voice vtuber makes her own art, plays elder ring, lived in japan
** Mu Yu Qian
half-nude asian servant-maid making cookies
artificial jaw
https://deltaporno.com/photos/mu-yu-qian-nude/
** Olga Kobzar
redhead almost butter-face, huge tits, naive sundresses
instagram@bugs_bunny_gf
** Saori Kiyomi
cosplay, inocentish(lewd) asian, seems natual
feel of: the girl that naively friendzones you
twitter@saorikiyomi
** Umeko J
mash: lewd egpytian white half nude cosplay; oily and collared; pink hair
asian
twitter@umekoj0910
** Hailey Leigh
brown haired, "destiny" tattoo at arm
white sweater, black bra, pigtails, college slut
instagram@haileyleighxo
** 404incorrect
4chan girl /g/ femcel, dropped out of school
green-gray-neon hair
tiktok@404incorrect
** Sally Fae
formelly Dawn Willow
chatubate.com@dawnwillow
twitter@sally_fae
blue eyes, dark hair fake blond, pink mate lipstick, cat eyelids
meshes, furry headsets, ring piercings, looks like younger gianna michaels
** Gianna Michaels
instagram@therealgianna_michaels
twitter@therealgianna
big titted slut, black hair and eyes
liked to force them into cumming inside her
** Octavia May
piercing in both of her cheeks
instagram@octaviamay.sg
instagram@itsoctaviamay
twitter@octaviamaysg
** Maria Fernanda
instagram@fegalvao_
brazil, barbie thick lips, blue eyes, black hair; cosplay: mikasa, hinata
** marty___rey
natalia poklonskaya daughter
russian crimea
https://www.instagram.com/marty___rey/
** Danielle Bregoli
instagram@bhadbhabie
4chan teenager with massive tits, now aged 29; lowlife ways, rapper
fake redhead partially latina, barbie face, black eyes
** Sara Mei Kasai :fav:
twitter@sarameikasai
pokemon tshirts and tattoes, black haired mate lipstick, sweater dresses
powerful dress
nerd face, cat(fox) girl, cute dresses videos, with slut rap music
** mollysbloomers89
reddit@mollysbloomers89
nerdy but slut vibes girl, pig tails, glasses
waiting for wedgie on her bed, skirt topless or top bottomless
** MiniLoona :fav:
huge tits, milk skin, brown eyes dark hair, clear aureola, no labia
velma, colegiala cosplay, what if I convince your bf? getting a yes
reddit@miniloona
twitter@mini_loona
tiktok@miniloonan
** Higashi
asian, fuck-me cross-stickers on tits, tight harneses and latex gloves
twitter@KawaiiHigashi
** Valeria Belen :fav:
twitter@Valeriaaa_belen
cow girl, huge tits, gordibuena; white skin, several colegiala outfits (seethrough)
argentina, chilena
gissele + daniella; cloths always tight to her tits & always perky
saw first in(and better than) Karipapauuu
** Paula Leal
twitter@PaulaPaulaeal
redhead, cat makeup, big tits
** Hot Lie
reddit@Hot_Lie_8901
brunnete, hipster glasses, bandage tattoo, barbie face(babe)
** eveliinushkaa
instagram@eveliinushkaa
russian red hair, trad wife, inocent face, sundress
** Irina Meier
instagram@irene_meier
redhead colegiala(squared) outfit; aztec feathers outfit
has been in teotihuacan
** Renata Ramos
brazileira
keyword: renata ramos vampire 69
pornhub@renata_matos
** iCuckoldress
blacked while hubby recorded from behind, thick not fat
twitter@icuckoldress
** Titty Kitty
cat girl, porn
twitter@tittikitti8
** Jewelz Blu
blue haired girl
twitter@jewelz_blu
** Lauren Dragneel
twitter@luarendragneel_
reddit@laurendragneel
instagram@lauren_dragneel
white haired, kirby-knife tattoo
pink bra, big tits, pov: her watching you from above
as a barista, with black sticks over aureolas and elf ears
** Hyoon
instagram@aikuros
twitter@floaromaa (art account)
cosplay, pretty asian that also draws (herself) anime; artist
** LATEXnCHILL
r/LATEXnCHILL
wears latex
** Neku_On_A_Leash
r/Neku_On_A_Leash
wears latex, nice body shape; white tshirt latex got banned too sexual
** hotwifekatrina
found in 8kun 8chan
https://twitter.com/hotwifekatrina
https://xxxredd.it/hotwifekatrina-gifs
** Anna Bell
pink haired slut full of tattoes, her tits are fake; butterfly at belly
reddit@annabellpeaks
** littlmisfit
reddit@littlmisfit
australian huge tits,I hope I have the type of body you would consider fucking
childish face
** onebigkiss
twitter@onebigkiss2
huge tits, vestido de lunares blanco, uses stars to cover her tits, blue-gray eyes
** MinaVie
reddit@MinaVie
work wife theme, black haired, short skirts
** Siri :fav:
reddit@Siripornstar
fake blonde, fake redhead, brownhair; huge tits, had breast reduction
video her and futbol player reward
** Annonalfa
reddit@annonalfa
cat eyelid, huge tits, thick, blonde
adorable face
** t0fuAndTitti3s
reddit@t0fuAndTitti3s
asian: chinese + argentinian, good lingerine huge tits
** Ashley Ann
reddit@ashleytervort
huge tits, mongolian skull
** GingerSPXCE :fav:
reddit@gingerspxce
natural redhead with black lipstick, huge tits, serpent-snake tongue between tits
natural slut-lewd face, sansa stark; 333 tattoo on neck
blue eyes
perfect for innocent > slut transformation (corruption)
vlad_o_chka_
reddit@vlad_o_chka_
brunette russian,, good skull juicy lips, dark green eyes
big natural tits, pale nipples, pale skin
only one tit pierced, sparce iconic tattoos across her body: spider tattoo (black widow)
you would think she is older due to the slutness
** Violet Myers
twitter@violetsaucy
latina brown cosplay
** Meladinha
her shape looks nice in heels
cosplays: tornado, bunny, shiro (green gray hair)
reddit@me1adinha
Coconut Kitty :fav:
instagram@coconutkitty143
artificial tits, latex, bimbo feel; big lips; brown hair, light blue eyes
reminds of tornado girl cosplayer
** msfiiire
- the farmer daughter, blond, reminds of old dancer with pink bra gif
- instagram.com@msfiiire
** Andrea Perez
Andrea Perez, xxxandrea, andreahotx, hotx2andrea
couldnt find photos in yandex, deleted
** iaaras2
instagram@iaaras2
argentinian cute faces short tiktoks
** Puppygirljenna
puppy dog roleplay
https://www.instagram.com/puppygirljenna/?hl=en
** BbustingStacy
https://twitter.com/BbustingStacy
bdsmlr girl castration roleplay BbustingStacy
** GENERIC ASIAN
FAV
[[https://twitter.com/SXeyes_][SXeyes]]
https://twitter.com/Takomayuyi
[[https://twitter.com/QianniuTT/][Qiaoniutt]], huge ass
https://twitter.com/chanbaekkailu1 big tits and cute
[[https://twitter.com/sinonome_umi][sinonome_umi]] [[https://www.youtube.com/channel/UCLnac6g3R8YcGOisZxsVIpw][youtube]] man hobbies
[[https://twitter.com/yummychiyo/][yummychiyo]] cosplay
https://twitter.com/senyamiku0 awesome cosplay like
[[https://twitter.com/Kuukow002][Kuukow002]] very thin, genshin, coolest fashion
https://twitter.com/Misanay1
[[https://weibo.com/u/6748748716][浅浅Princess]] huge breasts walking down the street <<FAVFAV
*YOUNG
[[https://twitter.com/chunmomo0127?lang=en][chunmomo0127]] perfect girl, tits big and young-cute face, [[https://www.instagram.com/chunmomo020127/][insta]]
[[https://twitter.com/seeu_cosplay][seeu_cosplay]]
**https://www.youtube.com/@seeu
*snexxxxxxx :fav:
the literally perfect asian girl, petite perfect young face, milky skin
nun cosplay,
https://twitter.com/snexxxxxxx
IN CHINA, CHINESE
- https://twitter.com/i/lists/1668902024526569472
- https://twitter.com/chengzimiaoj/
- https://twitter.com/chengzimiaoji1
- https://twitter.com/SubManL
- https://twitter.com/yunjin553366
- https://twitter.com/xizi1911
- https://twitter.com/yummychiyo
- https://twitter.com/Misanay1
- https://twitter.com/Meng_LuYa_/
BIG TITS
https://twitter.com/rissoft344
https://twitter.com/Misanay1
https://twitter.com/niyeye2019
https://twitter.com/jhuy3765
https://twitter.com/canan8181
https://twitter.com/Haiyi_NEKO
[[https://www.instagram.com/p/B8-b68Mg7rn/][ms_puiyi]] pandemic mask girl
[[https://twitter.com/ninja_azz?lang=en][NinJA_Azz]] cute asian girl smiling
CUTE
https://twitter.com/chanbaekkailu1
https://twitter.com/iorimoe_five
https://www.instagram.com/enakorin
https://www.instagram.com/amaukisumi/
https://twitter.com/kc_nemutai/
https://twitter.com/mntyoume
https://m.weibo.cn/u/5315541617
** CandyRobbs
twitter@candyrobbs1
ultra thick argentinan, huge tits and hips while very thin waist
** GoddessNikkiKit
reddit@GoddessNikkiKit
dominatrix, left bf at home while she went to vacation
playing with her strappon
** Olivia Cláudia Motta Casta
fine slut, dresses like lewd secretary
brown hair, big lips, dark-green eyes, big tits slender body
instagram@oliviacastaxx
** TlMisaki
twitter@TlMisaki
instagram@misaki_tl
tiktok@misakitl
very girly face woman, mexican
megumin outfit, cute outfits not (fully) lewd (yet)
** Motzie
reddit@Motziee
white thin, petite, and black hair
self described goth, has huge black-widow spider on her chest below tits
** angelicfuckdoll
reddit@angelicfuckdoll
blonde, massive tits
** Skylor
Nadine-J Skylor
https://nadine-j.de/models/photosets/latest
ukranian whose dad went back into ukraine
instagram@rima_yasashi
** AryaPumpkin :fav:favfav:
reddit@[[https://www.reddit.com/user/AryaPumpkin/][AryaPumpkin]]
most beautiful geeky girl, marin kitagawa, does cosplay
has dildo collection
** BralessForever
https://www.redgifs.com/users/bitchinbubba
goes around with her free-tits, usually no face
several women
** waifu.princess :fav:
- tiny weenie short dick mess, dance
  https://www.tiktok.com/@waifu.princess
  https://www.tiktok.com/@b1ggestregret
** secretlifeofsophiex :fav:
- big-huge tits redhead (carrot like)
- instagram@secretlifeofsophiex
** uwucaptain
Touki00 / uwucaptain666 / uwucaptain / touki
giant tits, milky skin, anon broke into her dad car and left photo evidence of her secret e-thot life
** laheldoll
[[https://www.reddit.com/user/laheldoll][user/laheldoll]]
fake redhead, huge tits, witch symbology
** Veronica Leal :fav:
colombiana, latina, carnedelmercado, vendedora de frutas
https://www.xvideos.com/video50772295/mamacitaz_-_colombian_amateur_babe_veronica_leal_loves_spontaneous_sex
** Jellybeannose :fav:
Dancing girl
https://youtu.be/Fg1TsNpkWgk
Jellybeannose ASMR Custom NSFW Video
https://www.pornmega.com/videos/138374/jellybeannose-asmr-custom-nsfw-video
** serenamello
https://www.instagram.com/serenamello/?hl=en
https://www.tiktok.com/@melloserena/video/7152589492703005994?is_copy_url=1&is_from_webapp=v1
* OTHER
** VIDEO
- anime - hentai - guro: torture
  - Magical Girl Spec-Ops Asuka
    - episode 4 (toasted belly red-heated clamps)
    - episode 8 (re-attach arm)
    - episode 12 (stabbed tit)
OTHER
- biggest bbc ever, would have to use trash bags as condoms
  - pretty flat blonde
  - https://video314.monstercockland.com/mcl/media/videos/mp4/291166.mp4
- black man fucking pale tattoed white skin, rough sex, some slaps
  - https://www.eporner.com/video-17CcmZRqFec/tattoed-sex-freak-gets-slutty-and-wild-with-bbc/
NTR
*FAV
https://www.xvideos.com/video24080809/tiffany_watson_gets_bbc_at_cuckold_sessions
https://xhamster.com/videos/interracial-lift-and-carry-xhBlXVu
https://xhamster.com/videos/lame-husband-watches-wife-enjoy-and-fuck-a-black-guy-xhVbjjH
by Layla Rivera
https://xhamster.com/videos/amber-blank-and-bbc-5241060

zooporn
https://es.luxu
retv.com/videos/su-perro-es-el-que-en-realidad-tiene-el-control-en-esta-relacion-133386.html
*OLD
https://javplay.me/nacr-303-an-ideal-bride-who-fulfills-her-husbands-desire-to-be-cuckold/
https://www.xvideos.com/video25822575/lame_husband_watches_wife_fuck_a_black.guy"
https://www.tnaflix.com/hd-videos/Sexy-British-babe-cheats-on-bf-with-black-cock-and-cums-on-his-dick-%21/video4318898?isFeatured=0
https://xhamster.com/videos/white-woman-rides-black-dick-until-he-creams-inside-her-13892479
https://xhamster.com/videos/she-came-for-bbc-10382232
https://xhamster.com/videos/reverse-cowgirl-for-white-bbc-slut-xhXLuAM
https://xhamster.com/videos/interracial-lift-and-carry-xhBlXVu
https://www.xvideos.com/video58547277/cuckold_blonde_fucks_bbc_couple :foursomeactuallyisthreesome:
https://www.xvideos.com/video24080809/tiffany_watson_gets_bbc_at_cuckold_sessions :blackliftsbf:
*JAV
**MEYD-568
**My Wife's Overtime NTR Work The Truth Is: I've Been Lying To My Husband about Working Overtime... Meguri.
**My Wife's Overtime NTR I Lie To My Husband And Work Overtime…. Tour
***TORRENT: 4246e4b6f8c39dd9df872bd499ef4cfd1f49810d
**Father-in-law's New Fucktoy - Saki Okuda (奥田咲) [SSIS-026]
**ADN-340
Nanami Matsumoto. ADN-340
ADN-340 Fucked In Front Of Her Husband - The Other Face Of The Nice Old Man, Nene Tanaka
https://w3.javsx.com/videos/adn-340-7279.html
**SCAT
- https://pornjav.org/sex-porn-scat/3871--defecation-2018-sl-071-hd-1280x720.html
  -  Defecation, Dirty enema, DLSL-071, Enema training, HD 720p, Jade scat, Sharila JADE, Sharila poop, Sharila scat, SL-071, シャリラ, ジェイド, 脱糞
YOUTUBE
*LEWD
- [[Jellybeannose]]
**Cat girls Japan
https://youtu.be/LwIm_TSvhyQ
**Slap Girls Ass Competition
https://youtu.be/ROCOArXk7Zc
**Miss Monique
green front hair, thin; likes to use crop tops
Progressive House - Melodic Techno DJ - Music
youtube@miss monique
*NTR YOUTUBE
- channel: sex positive gaming
**I Like Ugly B*****d Hentai And I'm Not Sorry
Syd
https://twitter.com/Sydsnap
https://youtu.be/s_K5ONweYd4
**Long Long Man - Chi Chan
japanese candy commercial
https://youtu.be/6-1Ue0FFrHY
** FEMDOM ANIMES
- Boku wa Kanri Kanri Kanri Sarete Iru
- Nagatoro
- Dress Up Darling
- Please Go Home, Akutsu-san!
- Isekai NTR
- Yancha Gal no Anjou-san
- My Life as Inukai-san's Dog
- Please Put These On, Takamine-san
- Tsumi to Kai
- JK Shachiku wo Kau
- Idol to Otaku no Risou no Kankei
- MM!
** CUCKOLD MOVIES
- The Boy Next Door, Cercana Obsesión: sleeps with mother teacher, fucks her-son crush and she witnesses it
** GORIC
- suspiria (movie)
- gurochan
  - gurochan.cx (site, vore)
** OTHER SITES
- xvideos
- xnxx.com
  - https://www.eporner.com/video-VnKRd5BMww8/bust-jerk-slap-whiteboy-wbch-special/
- pornhub
- bffs
- youthlust
