:PROPERTIES:
:ID:       4e22ce22-2f24-4373-b232-f6a5ea848efe
:END:
#+title: d20230629223412
#+filetags: :20230629223412:ntronary:
wife misses sexual contact with her husband who is working away, a new alfa neighbour moves in, one day she is masturbating and suddenly alfa appears inside her house and takes advantage of the situation (he let himself in since he heard a scream (he knew it was sexual tho)), he proceeds to regularily use he her while her husband is away, too when she speaks with him on the phone, and too when they are talking about having a baby, in the end alfa impregnates her the day hubby is meant to come back and he knows since he tested her juices. just the next day alfa goes out of his home to find a gorgeous girl waiting outside his neighbours house, it was her sister who came to live with her since her husband cheated on her, but she didnt got a chance to even see her, she let herself be used by that cute boy to get back at her husband. time later her sister invites wife to trip, and hubby insight discovers inside her sister car is non other than the neighbour, shocked but without choice gets in, later she finds the nature of that relationship and too that her sister knows that she is pregnant by the neighbour, the objective of the trip was for the sister to get pregnant too and also alfa gets his way into a threesome with the sisters. even tho sis recomended her to get an abortion she ultimately decided to have the neighbours baby, she also started to deceive her husband when going out to actually continue her affair, alfa too starts making her scream obsenities to her terror for her husband to hear and find out the truth across the wall but she is safe since when she is out he spends the time watching porn to releave himself of the sex that she hasnt been giving him. one day alfa leaves one of the videos in hubby porn collection with the her face blurred out (although that time he does suspect something for a second by the end), a video about cheating wifes who confess while fucking. the baby is born, by the time she comes back to home the neighbour moved away and so do them, years pass the daughter rises and out of no where one day alfa appears back and succesfully fucks her again despite some resistance and the pandora box is open once again, she finds he years back only moved away to prevent her from telling hubby the truth. she decides to give her daughter a sister or brother from her actual dad; when that daughter marries, alfa drugs her and fucks her own daughter on her wedding night
- [[id:6c02e84a-0bf9-4f03-9b17-e59a76f561fc][oᴗo]]
- TAG favfav
- NAME
[Carn] Wifeout [English] [Doujins.com] [Digital]
* LINK
https://nhentai.net/g/312021/
https://exhentai.org/g/1308651/7613b0e0aa/?p=7
