:PROPERTIES:
:ID:       f67f68d9-7dd3-4343-8f90-eb08aebc6089
:END:
#+title: d20230712155106
#+filetags: :20230712155106:ntronary:
Yukari Takase is easily influenced. During a school trip, she had sex with classmates and teachers other than her boyfriend. After getting to know men, Yukari's natural sexual desire runs wild and she can't stop masturbating.
She then pushes her cute little brother-type boyfriend-kun down halfway and attacks him in the cowgirl position. They fuck each other with their pussies overflowing with love juices. But Yukari is frustrated because her boyfriend is the first to cum. Moreover, the pillow talk is very lame, and the relationship cools down quickly.
A few days later, Yukari is embraced by her teacher. She wants a big, nice cock that is different from her boyfriend's. She lets herself be pleasured by it. There she finds a bitch who gives herself over to pleasure and shakes her hips on her own.
- [[id:c0b9ce52-8b8d-4eeb-a63b-629892df3888][oᴗo]]
- previous: [[id:1cffd71b-94ea-4158-b722-ee59ecc234bf][d20230712154827]]
- NAME
[Kurumaya Koudou] Shuugaku Ryokou, Kanojo Ubarareru Nettaiya -Ochiru Mesu Inu, Saru Kanojo-
* LINK
https://www.pixiv.net/en/artworks/109169449
