:PROPERTIES:
:ID:       417bc149-adf0-4915-b820-01423bcbcba3
:END:
#+title: d20230716062408
#+filetags: :20230716062408:ntronary:
>Sayoko Mikura moved to this village from the city.
>She was deeply disgusted by the closed atmosphere of the village and the people around her, who looked at her with a lecherous eye because she was more developed than other girls of her age.
>In addition, Sayoko's mother had been kicked out of the house because of an affair. This included Sayoko, who is not related to her father by blood.
>And after moving to her mother's home village, the women of the "Mikura family" are called "Shirahime-sama" by the people and are feared by them.
>So her classmates continued to avoid Sayoko as well. However, Kawase, who was in the next class, did not discriminate against Sayoko and talked to her.
>Kawase, like Sayoko, is from the city. He told her that he had moved to this village after his father's restructuring.
>Gradually, the two become close to each other, and they begin to have a physical relationship.
>Then, an incident occurs in the village.
>People appeared who were covered from the neck up with something black and became invisible. It was as if there were headless corpses walking around.
>When she was summoned by the grandfather of the Mikura family, Sayoko was told: "...That's why you are here... So, Sayoko, you must become the White Princess and save the people of the village. This is a mask that has been sealed by the Mikura family for generations. It is the duty of the Mikura family women to quell the curse that oozes from it.
>Sayoko, who has become the Shirohime-sama, uses her body to mingle with men, gain pleasure from them, and climax. She must save the people of the village by repeating this process...
- [[id:e7b2d722-a0c2-4958-a9f8-1b0ef56945df][oᴗo]]
- [[id:e83c2ec5-70c0-4c42-bdca-30027d5e89b3][FANTASY]] theme
- NAME
[Garakuta Shoujo (Miito Shido)] Ore-tachi no Sayoko Tokai kara Kita Ano Ko wa Ikenie de, Mura no Otoko-tachi no Omocha.
* LINK
https://hentaiera.com/gallery/1087053/
